#! /bin/sh

### autostart ###
xrandr --output HDMI-1 --mode 1366x768 &
~/.config/polybar/launch.sh &
sxhkd &
compton -b
numlockx on &
feh --bg-scale ~/Pictures/Wallpapers/space.png
wal -R &
autocutsel &
xsetroot -cursor_name left_ptr


### general stuff ###
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10
#bspc config focused_border_color "#D20104"
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a gpodder desktop='^2' state=floating
bspc rule -a firefox desktop='^1'
bspc rule -a Lutris desktop='^3'
bspc rule -a Upwork desktop='^2'
bspc rule -a Skype desktop='^4'
bspc rule -a keepassxc desktop ='^3'
bspc rule -a Screenkey manage=off

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

