#! /bin/sh

### autostart ###
~/.config/polybar/launch.sh &
xrandr --output HDMI-A-0 --auto  --primary
xrandr --output DVI-D-1 --auto --left-of HDMI-A-0
sxhkd &
numlockx on &
picom -b &
feh --bg-scale --no-xinerama ~/Pictures/Wallpapers/road.jpeg &
wal -R &
autocutsel &
xsetroot -cursor_name left_ptr

### general stuff ###
bspc wm -O HDMI-A-0 DVI-D-1
bspc monitor HDMI-A-0 -d I II III IV V
bspc monitor DVI-D-1 -d VI VII VIII IX X
bspc config border_width         2
bspc config window_gap          10
# bspc config focused_border_color "#D20104"
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a gpodder desktop='^2' state=floating
bspc rule -a Lutris desktop='^3'
bspc rule -a KeePassXC desktop ='^1'
bspc rule -a Discord desktop ='^3'
bspc rule -a Screenkey manage=off

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"
